
FROM docker:28-dind


RUN apk add --no-cache openssh-server && ssh-keygen -A

RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh

COPY *.pub /tmp/cles/

RUN cat /tmp/cles/*.pub > /root/.ssh/authorized_keys \
    && chmod 600 /root/.ssh/authorized_keys \
    && rm -rf /tmp/cles

RUN printf '#!/bin/sh\n/usr/sbin/sshd\nexec dockerd-entrypoint.sh "$@"\n' > /start.sh \
    && chmod +x /start.sh

    
ENTRYPOINT ["/start.sh"]
