name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test-backend:
    runs-on: ubuntu-latest
    services:

      mariadb:
        image: mariadb:11.4
        env:
          MARIADB_DATABASE: karaoke
          MARIADB_USER: karaoke
          MARIADB_PASSWORD: karaoke
          MARIADB_ROOT_PASSWORD: root

        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
 
      - name: Install dependencies
        run: npm ci
        working-directory: backend

      - name: Init database
        run: |
          mysql \
            -h 127.0.0.1 \
            -u karaoke \
            -pkaraoke \
            karaoke < database/mariadb/init.sql

      - name: Run tests
        run: npm test
        working-directory: backend
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USER: karaoke
          DB_PASSWORD: karaoke
          DB_NAME: karaoke

      - name: Check repository structure
        run: |
          pwd
          ls -la
          ls -la database
          
      - name: Create database schema
        run: |
          mysql \
            -h 127.0.0.1 \
            -u karaoke \
            -pkaraoke \
            karaoke < ./database/init.sql
 
      - name: Run integration tests
        working-directory: backend
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: karaoke
          DB_USER: karaoke
          DB_PASSWORD: karaoke
        run: npm test



  build-frontend:
    name: Build and push front docker image
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Check if front image already exist
      id: check_front_image
      shell: powershell
      run: |
        $ErrorActionPreference = "Continue"
        docker manifest inspect ${{ secrets.DOCKERHUB_USERNAME }}/j5-karaoke-front:${{ github.sha }} > $null 2>&1  
        if ($LASTEXITCODE -eq 0) {
            "exists=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            "exists=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }
        exit 0

    - name: Build and push front image if needed
      if: steps.check_front_image.outputs.exists == 'false'
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/j5-karaoke-front:${{ github.sha }}



  build-backend:
    name: Build and push back docker image
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Check if Backend image already exist
      id: check_backend_image
      shell: bash
      run: |
        if docker manifest inspect ${{ secrets.DOCKERHUB_USERNAME }}/j5-karaoke-back:${{ github.sha }} > dev/null 2>&1 
        then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
        exit 0
        

    - name: Build and push Backend image if needed
      if: steps.check_backend_image.outputs.exists == 'false'
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/j5-karaoke-back:${{ github.sha }}



  deploy:
    name:  Deploy
    runs-on: self-hosted
    needs: build-backend
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Test SSH
        shell: powershell
        run: |
          ssh -vvv -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "echo OK"


      - name: Copy compose file
        shell: powershell
        run: |
              scp -P ${{ secrets.DEPLOY_PORT }} ./todo/compose.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/srv/todo/compose.yml

      - name: Deploy application
        run: |
          ssh -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "cd /srv/todo && docker compose down && TAG=${{ github.sha }} docker compose up -d"

      - name: Health check
        run: |
          ssh -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "curl http://localhost:3000/health"




    # - name: Build the front Docker image
    #   run: docker build . --file Dockerfile --tag j5-karaoke-front:${{ github.sha }}

    # - name: Build the back Docker image
    #   run: docker build . --file Dockerfile --tag j5-karaoke-back:${{github.sha }}
        
    
    # - name: Push front on Docker Hub
    #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/j5-karaoke-front:${{ github.sha }}
    
    # - name: Push back on Docker Hub
    #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/j5-karaoke-back:${{ github.sha }}