name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:

      mariadb:
        image: mariadb:11.4
        env:
          MARIADB_DATABASE: karaoke
          MARIADB_USER: karaoke
          MARIADB_PASSWORD: karaoke
          MARIADB_ROOT_PASSWORD: root

        ports:
          - 3306:3306
        options: >-
          --health-cmd="healthcheck.sh --connect --innodb_initialized"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
 
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
 
      - name: Install dependencies
        working-directory: backend
        run: npm install
 
      - name: Check repository structure
        run: |
          pwd
          ls -la
          ls -la database
          
      - name: Create database schema
        run: |
          mysql \
            -h 127.0.0.1 \
            -u karaoke \
            -pkaraoke \
            karaoke < ./database/init.sql
 
      - name: Run integration tests
        working-directory: backend
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: karaoke
          DB_USER: karaoke
          DB_PASSWORD: karaoke
        run: npm test

  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with: 
        username: sakagnir
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Add front tag before push
    #   run: docker tag j5-karaoke-front:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/j5-karaoke-front:${{ github.sha }}
    
    # - name: Add back tag before push
    #   run: docker tag j5-karaoke-back:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/j5-karaoke-back:${{ github.sha }}

    - name: Check if front image already exist
      id: check_image
      run: |
        if docker manifest inspect \
          ${{ secrets.DOCKERHUB_USERNAME }}/karaoke-front:${{ github.sha }} > dev/null 2>&1
        then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Build and push front image if needed
      if: steps.check_image.outputs.exists == 'false'
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/j5-karaoke-front:${{ github.sha }}



    # - name: Build the front Docker image
    #   run: docker build . --file Dockerfile --tag j5-karaoke-front:${{ github.sha }}

    # - name: Build the back Docker image
    #   run: docker build . --file Dockerfile --tag j5-karaoke-back:${{github.sha }}
        
    
    # - name: Push front on Docker Hub
    #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/j5-karaoke-front:${{ github.sha }}
    
    # - name: Push back on Docker Hub
    #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/j5-karaoke-back:${{ github.sha }}